flyway.url=${DATABASE_URL}
flyway.user=${DATABASE_USER}
flyway.password=${DATABASE_PASSWORD}
flyway.locations=filesystem:infra/flyway/sql
flyway.sqlMigrationPrefix=V
flyway.sqlMigrationSeparator=__
flyway.sqlMigrationSuffixes=.sql
flyway.baselineOnMigrate=true
